from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.pagesizes import A3, landscape
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics
from config import POSTER_DIR
import re

class PosterService:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        # 尽量使用系统中文字体；找不到时回退 Helvetica，中文可能显示不完整。
        self.font_name = "Helvetica"
        for fp in [
            "/usr/share/fonts/truetype/wqy/wqy-microhei.ttc",
            "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
            "C:/Windows/Fonts/msyh.ttc",
            "/System/Library/Fonts/PingFang.ttc",
        ]:
            if Path(fp).exists():
                try:
                    pdfmetrics.registerFont(TTFont("CNFont", fp))
                    self.font_name = "CNFont"
                    break
                except Exception:
                    pass

    def _parse_sections(self, poster_text: str) -> dict:
        keys = ["TITLE", "BACKGROUND", "OBJECTIVE", "METHODS", "KEY FINDINGS", "CONTRIBUTIONS", "LIMITATIONS", "TAKEAWAY"]
        sections = {k: "" for k in keys}
        current = None
        for line in poster_text.splitlines():
            clean = line.strip()
            m = re.match(r"^(TITLE|BACKGROUND|OBJECTIVE|METHODS|KEY FINDINGS|CONTRIBUTIONS|LIMITATIONS|TAKEAWAY)\s*:\s*(.*)$", clean, re.I)
            if m:
                current = m.group(1).upper()
                if current == "KEY FINDINGS":
                    current = "KEY FINDINGS"
                sections[current] = m.group(2).strip()
            elif current:
                sections[current] += "\n" + clean
        return sections

    def create_poster_pdf(self, paper_id: str, title: str, poster_text: str) -> Path:
        out = POSTER_DIR / f"{paper_id}_academic_poster.pdf"
        doc = SimpleDocTemplate(
            str(out),
            pagesize=landscape(A3),
            rightMargin=1.2*cm,
            leftMargin=1.2*cm,
            topMargin=1.0*cm,
            bottomMargin=1.0*cm,
        )
        title_style = ParagraphStyle(
            "PosterTitle", parent=self.styles["Title"], fontName=self.font_name,
            fontSize=24, leading=30, alignment=1, textColor=colors.HexColor("#1F3A5F"), spaceAfter=14
        )
        h_style = ParagraphStyle(
            "SectionHeader", parent=self.styles["Heading2"], fontName=self.font_name,
            fontSize=14, leading=18, textColor=colors.white, backColor=colors.HexColor("#345C8C"), spaceAfter=8
        )
        body_style = ParagraphStyle(
            "PosterBody", parent=self.styles["BodyText"], fontName=self.font_name,
            fontSize=10.5, leading=14, spaceAfter=8
        )
        sections = self._parse_sections(poster_text)
        story = [Paragraph(title or sections.get("TITLE") or "Academic Poster", title_style)]
        cards = []
        for name in ["BACKGROUND", "OBJECTIVE", "METHODS", "KEY FINDINGS", "CONTRIBUTIONS", "LIMITATIONS", "TAKEAWAY"]:
            content = sections.get(name, "").replace("\n", "<br/>") or "待补充"
            card = [Paragraph(name, h_style), Paragraph(content, body_style)]
            cards.append(card)
        rows = [cards[:3], cards[3:6], [cards[6], "", ""]]
        table = Table(rows, colWidths=[13*cm, 13*cm, 13*cm], rowHeights=[8*cm, 8*cm, 6*cm])
        table.setStyle(TableStyle([
            ("VALIGN", (0,0), (-1,-1), "TOP"),
            ("BOX", (0,0), (-1,-1), 0.6, colors.HexColor("#D9E2EF")),
            ("INNERGRID", (0,0), (-1,-1), 0.4, colors.HexColor("#D9E2EF")),
            ("BACKGROUND", (0,0), (-1,-1), colors.HexColor("#F7FAFE")),
            ("LEFTPADDING", (0,0), (-1,-1), 10),
            ("RIGHTPADDING", (0,0), (-1,-1), 10),
            ("TOPPADDING", (0,0), (-1,-1), 10),
        ]))
        story.append(table)
        story.append(Spacer(1, 0.3*cm))
        story.append(Paragraph("Generated by Graduate Multi-Agent Literature System", body_style))
        doc.build(story)
        return out
